#include <iostream>
#include <string>
#include <windows.h>
#include <ctime>
using namespace std;

struct Element {
    string name;
    string symbol;
    string facts;
};

int main() {
    srand(time(NULL));
    Element elements[118];
    elements[0] = { "Hydrogen", "H", "Atomic number 1, most abundant element in the universe." };
    elements[1] = { "Helium", "He", "Low boiling point, used in balloons." };
    elements[2] = { "Lithium", "Li", "Used in batteries, can treat bipolar disorder." };
    elements[3] = { "Beryllium", "Be", "Lightweight and strong, used in aerospace." };
    elements[4] = { "Boron", "B", "Used in cleaning products, semiconductor industry." };
    elements[5] = { "Carbon", "C", "Basis of life, exists in various forms (diamond, graphite)." };
    elements[6] = { "Nitrogen", "N", "Makes up the majority of the Earth's atmosphere." };
    elements[7] = { "Oxygen", "O", "Essential for human respiration and combustion." };
    elements[8] = { "Fluorine", "F", "Used in toothpaste and water fluoridation." };
    elements[9] = { "Neon", "Ne", "Used in neon signs, a noble gas." };
    elements[10] = { "Sodium", "Na", "Reacts violently with water, used in salt production." };
    elements[11] = { "Magnesium", "Mg", "Used in alloys and as a dietary supplement." };
    elements[12] = { "Aluminum", "Al", "Lightweight, used in aircraft, packaging." };
    elements[13] = { "Silicon", "Si", "Key element in semiconductors and computer chips." };
    elements[14] = { "Phosphorus", "P", "Important for DNA, bone health, and fertilizers." };
    elements[15] = { "Sulfur", "S", "Used in chemicals, matches, and vulcanization." };
    elements[16] = { "Chlorine", "Cl", "Used in water treatment, bleach, and PVC production." };
    elements[17] = { "Argon", "Ar", "A noble gas, used in welding and lighting." };
    elements[18] = { "Potassium", "K", "Essential for plant and animal life, used in fertilizers." };
    elements[19] = { "Calcium", "Ca", "Important for bones, teeth, and muscle function." };
    elements[20] = { "Scandium", "Sc", "Used in aluminum alloys and aerospace materials." };
    elements[21] = { "Titanium", "Ti", "Strong, lightweight metal, used in aircraft." };
    elements[22] = { "Vanadium", "V", "Used in steel production and as a dietary supplement." };
    elements[23] = { "Chromium", "Cr", "Used for corrosion resistance and in stainless steel." };
    elements[24] = { "Manganese", "Mn", "Used in steel production and as a dietary nutrient." };
    elements[25] = { "Iron", "Fe", "Essential for hemoglobin, used in construction." };
    elements[26] = { "Cobalt", "Co", "Used in magnets, batteries, and alloy production." };
    elements[27] = { "Nickel", "Ni", "Used in alloys and coinage." };
    elements[28] = { "Copper", "Cu", "Good conductor of electricity, used in wiring." };
    elements[29] = { "Zinc", "Zn", "Used in galvanization and dietary supplements." };
    elements[30] = { "Gallium", "Ga", "Used in semiconductors and medical thermometers." };
    elements[31] = { "Germanium", "Ge", "Used in electronics and fiber-optic applications." };
    elements[32] = { "Arsenic", "As", "Used in semiconductors and pesticides." };
    elements[33] = { "Selenium", "Se", "Used in electronics and dietary supplements." };
    elements[34] = { "Bromine", "Br", "Used in flame retardants and photography." };
    elements[35] = { "Krypton", "Kr", "Used in lighting and laser applications." };
    elements[36] = { "Rubidium", "Rb", "Used in research and some atomic clocks." };
    elements[37] = { "Strontium", "Sr", "Used in fireworks and in some medical applications." };
    elements[38] = { "Yttrium", "Y", "Used in alloys and electronics." };
    elements[39] = { "Zirconium", "Zr", "Used in nuclear reactors and jewelry." };
    elements[40] = { "Niobium", "Nb", "Used in superconductors and alloy production." };
    elements[41] = { "Molybdenum", "Mo", "Used in alloys and electrical contacts." };
    elements[42] = { "Technetium", "Tc", "Radioactive, used in medical imaging." };
    elements[43] = { "Ruthenium", "Ru", "Used in electronics and catalysts." };
    elements[44] = { "Rhodium", "Rh", "Used in catalytic converters and jewelry." };
    elements[45] = { "Palladium", "Pd", "Used in catalytic converters and jewelry." };
    elements[46] = { "Silver", "Ag", "Used in coins, jewelry, and photography." };
    elements[47] = { "Cadmium", "Cd", "Used in batteries and pigments." };
    elements[48] = { "Indium", "In", "Used in electronics and LCD screens." };
    elements[49] = { "Tin", "Sn", "Used in solder and coatings." };
    elements[50] = { "Antimony", "Sb", "Used in flame retardants and alloys." };
    elements[51] = { "Tellurium", "Te", "Used in semiconductors and alloys." };
    elements[52] = { "Iodine", "I", "Used in medicine, photography, and as a disinfectant." };
    elements[53] = { "Xenon", "Xe", "Used in lighting and medical imaging." };
    elements[54] = { "Cesium", "Cs", "Used in atomic clocks and drilling fluids." };
    elements[55] = { "Barium", "Ba", "Used in medical imaging and fireworks." };
    elements[56] = { "Lanthanum", "La", "Used in catalysts and carbon arc lamps." };
    elements[57] = { "Cerium", "Ce", "Used in catalytic converters and as a polishing agent." };
    elements[58] = { "Praseodymium", "Pr", "Used in alloys and rare earth magnets." };
    elements[59] = { "Neodymium", "Nd", "Used in magnets and lasers." };
    elements[60] = { "Promethium", "Pm", "Radioactive, used in atomic batteries." };
    elements[61] = { "Samarium", "Sm", "Used in magnets and nuclear reactors." };
    elements[62] = { "Europium", "Eu", "Used in phosphors for color TV screens." };
    elements[63] = { "Gadolinium", "Gd", "Used in magnetic resonance imaging (MRI)." };
    elements[64] = { "Terbium", "Tb", "Used in color TV tubes and fluorescent lamps." };
    elements[65] = { "Dysprosium", "Dy", "Used in magnets and nuclear reactors." };
    elements[66] = { "Holmium", "Ho", "Used in high-strength magnets." };
    elements[67] = { "Erbium", "Er", "Used in fiber-optic communication." };
    elements[68] = { "Thulium", "Tm", "Used in portable X-ray devices." };
    elements[69] = { "Ytterbium", "Yb", "Used in laser technology and alloy production." };
    elements[70] = { "Lutetium", "Lu", "Used in positron emission tomography (PET)." };
    elements[71] = { "Hafnium", "Hf", "Used in nuclear reactors and aerospace materials." };
    elements[72] = { "Tantalum", "Ta", "Used in electronic components and alloys." };
    elements[73] = { "Tungsten", "W", "High melting point, used in light bulbs." };
    elements[74] = { "Rhenium", "Re", "High melting point, used in jet engines." };
    elements[75] = { "Osmium", "Os", "Densest naturally occurring element." };
    elements[76] = { "Iridium", "Ir", "Used in electrical contacts and in jewelry." };
    elements[77] = { "Platinum", "Pt", "Used in catalytic converters and jewelry." };
    elements[78] = { "Gold", "Au", "Highly valued for jewelry and as a monetary standard." };
    elements[79] = { "Mercury", "Hg", "Liquid at room temperature, used in thermometers." };
    elements[80] = { "Thallium", "Tl", "Used in electronics and as a poison." };
    elements[81] = { "Lead", "Pb", "Used in batteries and as a building material." };
    elements[82] = { "Bismuth", "Bi", "Used in medicine and as a replacement for lead." };
    elements[83] = { "Polonium", "Po", "Radioactive, used in some nuclear applications." };
    elements[84] = { "Astatine", "At", "Radioactive, occurs naturally in trace amounts." };
    elements[85] = { "Radon", "Rn", "Radioactive noble gas, used in some medical applications." };
    elements[86] = { "Francium", "Fr", "Highly radioactive, occurs in trace amounts." };
    elements[87] = { "Radium", "Ra", "Radioactive, used in early radioluminescent devices." };
    elements[88] = { "Actinium", "Ac", "Radioactive, used in radiation therapy research." };
    elements[89] = { "Thorium", "Th", "Radioactive, used in nuclear reactors and as a catalyst." };
    elements[90] = { "Protactinium", "Pa", "Radioactive, used in nuclear reactors." };
    elements[91] = { "Uranium", "U", "Used in nuclear power and weapons." };
    elements[92] = { "Neptunium", "Np", "Radioactive, used in nuclear research." };
    elements[93] = { "Plutonium", "Pu", "Radioactive, used in nuclear weapons." };
    elements[94] = { "Americium", "Am", "Radioactive, used in smoke detectors." };
    elements[95] = { "Curium", "Cm", "Radioactive, used in research and industry." };
    elements[96] = { "Berkelium", "Bk", "Radioactive, used in scientific research." };
    elements[97] = { "Californium", "Cf", "Radioactive, used in neutron sources." };
    elements[98] = { "Einsteinium", "Es", "Radioactive, used in research." };
    elements[99] = { "Fermium", "Fm", "Radioactive, used in nuclear physics research." };
    elements[100] = { "Mendelevium", "Md", "Radioactive, used in scientific research." };
    elements[101] = { "Nobelium", "No", "Radioactive, used in nuclear physics research." };
    elements[102] = { "Lawrencium", "Lr", "Radioactive, used in nuclear physics research." };
    elements[103] = { "Rutherfordium", "Rf", "Radioactive, synthetic element." };
    elements[104] = { "Dubnium", "Db", "Radioactive, synthetic element." };
    elements[105] = { "Seaborgium", "Sg", "Radioactive, synthetic element." };
    elements[106] = { "Bohrium", "Bh", "Radioactive, synthetic element." };
    elements[107] = { "Hassium", "Hs", "Radioactive, synthetic element." };
    elements[108] = { "Meitnerium", "Mt", "Radioactive, synthetic element." };
    elements[109] = { "Darmstadtium", "Ds", "Radioactive, synthetic element." };
    elements[110] = { "Roentgenium", "Rg", "Radioactive, synthetic element." };
    elements[111] = { "Copernicium", "Cn", "Radioactive, synthetic element." };
    elements[112] = { "Nihonium", "Nh", "Radioactive, synthetic element." };
    elements[113] = { "Flerovium", "Fl", "Radioactive, synthetic element." };
    elements[114] = { "Moscovium", "Mc", "Radioactive, synthetic element." };
    elements[115] = { "Livermorium", "Lv", "Radioactive, synthetic element." };
    elements[116] = { "Tennessine", "Ts", "Radioactive, synthetic element." };
    elements[117] = { "Oganesson", "Og", "Radioactive, synthetic element." };
    int choice, randy;
    while (true)
    {
        cout << "Hello! Welcome to our encyclopedia of periodic elements 'Choogle'! You may try to find some interesting facts about some chemical elements, or just feel lucky :)";
    }
}
